import "./globals.css";

// components
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// context
import { AppProvider } from "./context/context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <AppProvider>{children}</AppProvider>
        <Footer />
      </body>
    </html>
  );
}
